<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PE-GOL.DTO\PE-GOL.DTO.csproj" />
    <ProjectReference Include="..\PE-GOL.DAL\PE-GOL.DAL.csproj" />
    <ProjectReference Include="..\PE-GOL.Entity\PE-GOL.Entity.csproj" />
    <ProjectReference Include="..\PE-GOL.Utility\PE-GOL.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PE_GOL.BLL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
